on: push
name: deploy
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Install and Build
              run:
                  cd web &&
                  npm install &&
                  npm run build &&
                  npm run export

            - name: Deploy
              uses: dswistowski/surge-sh-action@v1
              with:
                  domain: 'horariosxdxd.surge.sh'
                  project: 'web/out/'
                  login: ${{ secrets.surge_login }}
                  token: ${{ secrets.surge_token }}
                                                 
